### ISSUE TITLE
Interrupt on Leonardo and PWM pin 6

### ISSUE THREAD

**Issue by SorX14** [z3t0/Arduino-IRremote#101]
I'm just using the output of the library, specifically the NEC remote codes. I'm also using PWM on pin 6, which stops functioning as a PWM pin, and acts as if its a standard digital pin (only `HIGH` and `LOW`).

Now, I understand that on the Leonardo (ATmega32u4) that Timer 4 is being used to modulate the output for the IR LED's, but it also deals with PWM on pin 6. As I've made a PCB and didn't breadboard my design(!) I want to be able to use pin 6 with PWM, and also use the IRremote library on pin 13.

I don't need PWM at the same time as sending an IR code, so is there a way to re-enable the standard PWM functionality after sending an IR code?

**Comment by z3t0** [comment]
@shirriff Any ideas

**Comment by AnalysIR** [comment]
In the defines for Timer4_HS, which is used by default for Leonardo.... there are some defines for functions
TIMER_DISABLE_PWM
&
TIMER_CONFIG_NORMAL()

You could try using either or both of these.

Some of the other defines, seem to overwrite other settings via '=' rather than '|' when setting the registers...eg. TIMER_ENABLE_INTR    (TIMSK4 = _BV(OCIE4A))

Also, remember that IR remote takes over control of the clock for Timer 4, which alone could upset your usage.

Workarounds:
1. Using the above functions, disable/enable Timer4 as needed for IR sending and also remember to re-init your own PWM when needed.
2. ...or....Just configure IRremote to use another Timer (Timer1 on pin9?) on the Leonardo, that doesn't conflict with your usage.

NB: untested!

**Comment by z3t0** [comment]
The relevant information can be found in the timer defines of the documentation for ATMega32u4
