### ISSUE TITLE
about RC5 second bit and RC6 mode6

### ISSUE THREAD

**Issue by lxbzmy** [z3t0/Arduino-IRremote#14]
Hi author,
First of all, this a good script and I like it.
 After  researched  many specification about RC5 and RC6 (gogole pronto.pdf),
After researching many specifications about RC5 and RC6 I found [this](http://www.majority.nl/files/pronto.pdf ?)

I found that your RC5 RC6  function need patch to support RC5x and RC6A.

This is my patched version:

``` c
/**
* Note: first bit must be a one (start bit)
* first bit always one, second bit may 0 or 1(pronto.pdf) 0 means command bit will add 64 
*/
void IRsend::sendRC5(unsigned long data, char nbits)
{
  enableIROut(36);
  data = data << (32 - nbits);
 /*  space(RC5_T1);
  mark(RC5_T1); // First start bit
  space(RC5_T1); // Second start bit
  mark(RC5_T1); // Second start bit */
  for (int i = 0; i < nbits; i++) {
    if (data & TOPBIT) {
      space(RC5_T1); // 1 is space, then mark
      mark(RC5_T1);
    } 
    else {
      mark(RC5_T1);
      space(RC5_T1);
    }
    data <<= 1;
  }
  space(0); // Turn off at end
}



/** according rc6 mode 6 data bits may be 32bit ,total bits will be 36bit(3 mode bit 1 toggle),this is over flow long data type
 * Caller needs to take care of flipping the toggle bit
 * @param mode toggle bit(0 or 1) mode bit is locked to 110
 * @param data unsigned 32 bit int
 * @param nbits 24 or 32. see pronto.pdf RC6A.
**/
void IRsend::sendRC6(char head,unsigned long data, char nbits)
{
  enableIROut(36);
  data = data << (32 - nbits);
  mark(RC6_HDR_MARK);
  space(RC6_HDR_SPACE);
  mark(RC6_T1); // start bit
  space(RC6_T1);
  //begin mode bit

  //begin data bit
  int t;
  head <<=4;//only need lower 4bit
  for (int i = 0; i < 3; i++) {
    if (head & 0x80) {
      mark(RC6_T1);
      space(RC6_T1);
    } 
    else {
      space(RC6_T1);
      mark(RC6_T1);
    }
    head <<= 1;
  }
  //tg bit
  if (head & 0x80) {
      mark(RC6_T2);
      space(RC6_T2);
  }else {
      space(RC6_T2);
      mark(RC6_T2);
  }
  //loop 
   for (int i = 0; i < nbits; i++) {
    if (data & TOPBIT) {
      mark(RC6_T1);
      space(RC6_T1);
    } 
    else {
      space(RC6_T1);
      mark(RC6_T1);
    }

    data <<= 1;
  }
  space(0); // Turn off at end
}

```

**Comment by z3t0** [comment]
Has this beemn solved...

**Comment by csBlueChip** [comment]
@lxbzmy Hello, I have just seen your patch.
= You speak of "pronto.pdf", where can I find this?
= In RC5, you say "first bit always one, second bit may 0 or 1(pronto.pdf) 0 means command bit will add 64" ...but you have /*removed*/ the header code, so the first bit can now be a 0 ...Can you explain please?
= In RC6, you say "  //tg bit ...  if (head & 0x80) {" ...but by the time this code is executed "head & 0x80" will ALWAYS be 0 (because of "head <<= 1" in the previous loop) ...What was your intention here?

**Comment by kylegordon** [comment]
Possibly http://www.majority.nl/files/pronto.pdf ?

On 21 June 2015 at 16:50, BlueChip <notifications@github.com> wrote:

> @lxbzmy <https://github.com/lxbzmy> Hello, I have just seen your patch.
> = You speak of "pronto.pdf", where can I find this?
> = In RC5, you say "first bit always one, second bit may 0 or 1(pronto.pdf)
> 0 means command bit will add 64" ...but you have /*removed*/ the header
> code, so the first bit can now be a 0 ...Can you explain please?
> = In RC6, you say " //tg bit ... if (head & 0x80) {" ...but by the time
> this code is executed "head & 0x80" will ALWAYS be 0 (because of "head <<=
> 1" in the previous loop) ...What was your intention here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shirriff/Arduino-IRremote/issues/14#issuecomment-113916118>
> .
>



-- 
Kyle Gordon - 2M1DIQ
Web: http://lodge.glasgownet.com
Jabber/Email/SIP: kyle@lodge.glasgownet.com

**Comment by csBlueChip** [comment]
@kylegordon I think you may be correct - your google-fu is strong :) ...Thanks.

**Comment by z3t0** [comment]
I have edited the original post to make it easier to find sources of information.

**Comment by mariusoei** [comment]
After a whole lot of messing around, I stumbled upon this: [Post about RC5x](http://lirc.10951.n7.nabble.com/Marantz-RC5-22-bits-Extend-Data-Word-possible-with-lircd-conf-semantic-td9784.html)

Setting the second bit to zero adds another 64 possible commands.
When I looked up the codes for my Marantz amp, they were divided into system, command and sometimes extension (a command toggles or changes a state, but with the extension it can be set to discrete values.
For the amplifier to know that there will be an extension, there has to be a 2 cycle low signal after the system id. This is neither a 1 (low, high) nor a 0 (high, low). 

It's probably easier to show in code, so I propose a change like this:

```
void IRsend::sendRC5(unsigned long data, int nbits)
{
  enableIROut(36);
  data = data << (32 - nbits);
  mark(RC5_T1); // First start bit (always 1)
  // second start bit to be set by user
  /*space(RC5_T1); // Second start bit
  mark(RC5_T1);*/ // Second start bit
  for (int i = 0; i < nbits; i++) {
    if (data & TOPBIT) {
      space(RC5_T1); // 1 is space, then mark
      mark(RC5_T1);
    } 
    else {
      mark(RC5_T1);
      space(RC5_T1);
    }
    data <<= 1;
	// if this command is longer than standard RC5,
	// we use the RC5x protocol, which includes 2
	// low cycles (4 spaces) after the device id
	if ((nbits > 13)&&(i==6)){
		space(RC5_T1);
		space(RC5_T1);
		space(RC5_T1);
		space(RC5_T1);
	}
  }
  space(0); // Turn off at end
}
```

This worked with my amplifier, without the additional spaces it doesn't.

**Comment by AnalysIR** [comment]
@mariusoei 
It may be better to create a complete new protocol definition for RC5X vs merging it with standard RC5.
It will also make it easier & more efficient to add in decoding support as well.
It will also make it easier to maintain.
Finally, for it to be included in the library, you need to create a pull request.

Also consider changing 
`space(RC5_T1);`
`space(RC5_T1);`
`space(RC5_T1);`
`space(RC5_T1);`

to 

`space(RC5_T1<<2);`

**Comment by mariusoei** [comment]
@AnalysIR 
Thanks for the feedback. I'm really new to the whole open source thing.

First, I'm not sure if it's already RC5x if the second bit is set to zero, but no spaces and no extension are sent. So maybe a definition for RC5x would have to include this case too, even though it has the same structure as standard RC5.

The 3 different bit streams are:

Standard RC5: 1 1 system command
Maybe RC5x (definitely added later): 1 0 system command   (this adds 64 to the command value)
Definitely RC5x: 1 1 system *pause, pause* command extension

Also, at least Marantz (and I'm sure most other sources) have their commands separated into these 3 numbers (system, command, extension). So if a user wanted to create a complete RC5 signal (like I did), he'd have to know that the system is 5 bits long and the command 6 bits.
Then he'd have to convert the system and command to binary, pad them to the right length and concatenate before entering them in the code.

Do you think it would make sense to add a wrapper function that does all this? 
Like `sendRC5x(int system, int command, int extension)`? The number of bits wouldn't even be a necessary input because it's defined in the protocol anyway.
I could code that, but where would you recommend I put it?

**Comment by AnalysIR** [comment]
I suspect the RC5x is defined by the long space in the middle and extra bits.

I think just setting it up with its own set of files/defines as a new protocol is the optimium approach.
Dropping the #bits would make sense.

To add it to the library, there is a a process on GitHub for PRs (pull requests). Sorry to say, google is your friend here, unless others can point to a getting started guide. I don't fully understand it - but managed to stumble thru it somehow.

Essentially you make a clone of the library, make your changes and submit it back to this repository as a PR for comments/inclusion/consideration.
