### ISSUE TITLE
Experimental Rewrite

### ISSUE THREAD

**Issue by z3t0** [z3t0/Arduino-IRremote#200]
I am going to be spending some time delving through the source code and essentially rewriting it with support for [OpenIR](Github.com/z3t0/OpenIr). The main effects would be some medium level changes in the effect of refactoring how some things work and adding an interface for OpenIR. This Interface includes being able to receive and send IR data (from the Arduino) by using OpenIR.

**Comment by bengtmartensson** [comment]
Please consider [Girs](http://www.harctoolbox.org/Girs.html) as communication protocol between the Arduino and the host program. This is an attempt at a general "communication language" between "servers" and "clients", in order to achieve a certain universality.  (No need to invent a new communication protocol for every new hardware.)

Sure, the specification in the link contains a number of "holes", but these can be specified.
