### ISSUE TITLE
Please add your library to Arduino Library Manager

### ISSUE THREAD

**Issue by ffissore** [z3t0/Arduino-IRremote#229]
Please consult https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ and submit request for inclusion into Arduino Library Manager

**Comment by pcoughlin** [comment]
Good idea.  There seem to be several files that are required for inclusion, with some specific formatted information ("library.properties" for one).

If anyone would like to write those additional files, then it will speed up this process.

**Comment by per1234** [comment]
It looks like it's all ready to go as is. The library.properties file already exists and is correctly formatted. The FAQ linked by ffissore above makes it sound like the source files might need to be moved to a src subfolder but from reading this: https://github.com/FastLED/FastLED/issues/159#issuecomment-98837773 it turns out to be optional. So someone just needs to submit an issue to https://github.com/arduino/Arduino/issues requesting the library to be added to Library Manager. I'd be happy to do so, just give me the go ahead.

**Comment by pcoughlin** [comment]
That i OK with me.  Please post the info you receive back and if there is some way to check the status (a link, I suppose), then please post that as well.

If you get into it and there are some sorts of encryption keys or something, then please let me know and maybe I might need to do it.

Other than that ... "Go Ahead"

**Comment by per1234** [comment]
Ok, issue has been submitted: https://github.com/arduino/Arduino/issues/4108 I'll let you know when it is added or if there are any issues.

**Comment by pcoughlin** [comment]
Well done.

**Comment by per1234** [comment]
IRremote has been added to the Arduino IDE Library Manager and I have successfully installed it.

**Comment by pcoughlin** [comment]
Very good @per1234 
This is a wonderful step.
