### ISSUE TITLE
SONY_DOUBLE_SPACE_USECS used wrongly?

### ISSUE THREAD

**Issue by matthijskooijman** [z3t0/Arduino-IRremote#36]
SONY_DOUBLE_SPACE_USECS is defined to 500, apparently meaning 500us. However, the code that uses it says:

```
  if (results->rawbuf[offset] < SONY_DOUBLE_SPACE_USECS) {
    // Serial.print("IR Gap found: ");
    results->bits = 0;
    results->value = REPEAT;
    results->decode_type = SANYO;
    return DECODED;
  }
```

Which looks like it compares with number of ticks, not microseconds. Effectively this means that this code is triggered whenever there are less than 25ms between two signals.

This looks wrong, but I'm not actually sure what this code is supposed to do, so I can't really suggest a useful fix.

**Comment by z3t0** [comment]
Thanks for pointing this out, I will see if I can figure it out

**Comment by EMurmel** [comment]
Hi ,
thanks for this great library!
I was trying to use an ancient SONY remote control (VTR/TV RMT-V137A).
With the IR dumper InfraredDumper.ino with some keys I got unreliable results with changing values and some with REPEAT-values following the actual value (I think it was FFFFFF).
Having seen this issue I tried to change SONY_DOUBLE_SPACE_USECS to 10 (instead of 500) as suggested by @matthijskooijman .
With this I'm getting reliable values for the keys !
I didn't do any more debugging, maybe I can find some time to have a look at the signals with an oscilloscope ...
Thanks !

**Comment by AnalysIR** [comment]
@EMurmel 
please post a dump of the signals you recorded.

**Comment by EMurmel** [comment]
@AnalysIR 
what type of dump do you mean ?

**Comment by AnalysIR** [comment]
@EMurmel 
The output of the example sketch:
[IRrecvDumpV2](https://github.com/z3t0/Arduino-IRremote/blob/master/examples/IRrecvDumpV2/IRrecvDumpV2.ino)

**Comment by EMurmel** [comment]
@AnalysIR 
ok, I hope I can manage tonight ...

**Comment by EMurmel** [comment]
Finally I managed to spend some time with the Arduino ...
My impression of "unreliable" values obviously partly was caused by some noise combined with getting "FFFFFFFF " values for repeats.
After getting rid of the noise I fetched some dumps:

I modified IRrecvDumpV2 by disabling output of raw and code values since this takes that much time that I will always get only one value whenI press the key shortly.

now the dumps (always pressing key "Volume -" shortly one time, similar results with some other keys):
with SONY_DOUBLE_SPACE_USECS    500:
```
Encoding  : SONY
Code      : C90 (12 bits)

Encoding  : SANYO
Code      : FFFFFFFF (0 bits) 

Encoding  : SANYO
Code      : FFFFFFFF (0 bits)
```



with SONY_DOUBLE_SPACE_USECS    10:
```
Encoding  : SONY
Code      : C90 (12 bits)

Encoding  : SONY 
Code      : C90 (12 bits)

Encoding  : SONY
Code      : C90 (12 bits)

```
Since I read in Ken Shirriff's excellent articles that (SONY) transmissions are sent a minimum of 3 times the second looks better for me although I currently can't figure out the evidence looking into code and raw signals!!
I don't know if "FFFFFFFF" REPEAT values do make any sense with the Sone IR remote control.

**Comment by AnalysIR** [comment]
@EMurmel It is not possible to review your signal without the RAW output.

> I don't know if "FFFFFFFF" REPEAT values do make any sense with the Sone IR remote control.

Agreed, particularly when it is shown as SANYO, instead of SONY. Either way the FFFFFFFF is meaningless here. It also shouldnt be considered as a repeat, unless the signal was sent more than 3 times.

**Comment by EMurmel** [comment]
@AnalysIR
SANYO or UNKNOWN is hardcoded for this special case (after comparing with SONY_DOUBLE_SPACE_USECS) in IRrecv::decodeSony()

Like described before when enabling raw output I'm getting only one value, for me it looks like I'm getting only the first of the minimum-3 transmissions:
```
Encoding  : SONY
Code      : E10 (12 bits)
Timing[25]: 
     +2500, - 550     +1250, - 600     +1250, - 550     +1300, - 550 
     + 700, - 550     + 700, - 550     + 700, - 600     + 650, - 600
     +1250, - 550     + 700, - 600     + 650, - 600     + 650, - 600
     + 650

```
and this is the same (apart from +-50 noise which I have always on subsequent keystrokes)
regardless if I use  SONY_DOUBLE_SPACE_USECS 500 or 10

I suppose this SW dump method can't be used in this case (analysing SONY transmitting 3x per keystroke ) ... but currently I don't have enough time to use the oscilloscope and understand the raw signals and encoding :-( 
Maybe I should use some minimum delay (like dumping raw and code :-) ) before re-enabling IR receiving to make sure I don't count more than one keystroke due to SONY-minimum-3x-transmissions. 
The question is do all SONYs use minimum 3 transmissions? 
...Or maybe I'm understanding nothing :-)

**Comment by AnalysIR** [comment]
@z3t0 , @EMurmel 
The code
```
#	ifdef DECODE_SANYO
		results->decode_type = SANYO;
#	else
		results->decode_type = UNKNOWN;
# endif
```
seems out of place in the SONY decoding. (IRrecv::decodeSony())
Maybe it is an editing artefact???

Also, the implementation of the 
`SONY_DOUBLE_SPACE_USECS`

also seems a bit weird. It might be worth checking when these changes were made and **re-** validating them.

**Comment by EMurmel** [comment]
@AnalysIR : thanks a lot for your review, for me also this looked a bit weird ...

**Comment by z3t0** [comment]
@AnalysIR @EMurmel 

I apologize it must have been a refactoring error somewhere. I'll try to track it down and then fix it.

Tracking:
- [8e243fe068](https://github.com/z3t0/Arduino-IRremote/commit/88e243fe068e06d2ed602fefe6bd5effd07006e1#diff-3da05b76b5faa317d1a324ce2f93781dL389)
- [9170c0b4a12219b] (https://github.com/z3t0/Arduino-IRremote/blob/9170c0b4a12219b5e83b56d638a7c82c0309b211/IRremote.cpp#L631)

This could take a while to trace...

**Comment by z3t0** [comment]
Okay so I managed to track it down to the last commit on the previous post and as far as I can tell it was a refactoring error as the sanyo protocol implementation was created as a modification of the one for sony (as far as I can tell).
