### ISSUE TITLE
Use aa2408 module

### ISSUE THREAD

**Issue by nunomsant** [z3t0/Arduino-IRremote#393]
Module: https://anyforsales.com/en/50ma-infrared-emitter-transmitter-module-with-38k-carrier-circuit-for-arduino-aa2804

It's possible tu use a ir module that generates it's own carrier frequency with this library?

In theory we can use any digital output and several emitters in the same board.

What changes are necessary?

Thanks

**Comment by AnalysIR** [comment]
You would just have to change the mark function to only turn the IO HIGH, instead of using the PWM to generate the carrier and change the space function to turn the IO LOW.

You would also be restricted to 38kHz. Also, the frequency of that module would be succeptible to drift with temperture. The bonus is that you can use any IO pin for IR Tx.

Another approach would be to look at the cuircuit & short out the carrier generation part. The signal from an Arduino would be much more accurate = better performance & longer range.

FYI: the stated 50mA is a bit of an exaggeration...more like 38mA peak @5V supply.

**Comment by nunomsant** [comment]
Ok thank you. This is very helpful, because I need to control several AC systems.

**Comment by nunomsant** [comment]
Another question: what range do you think this module can achieve?

**Comment by AnalysIR** [comment]
Hard to say...maybe 3-5m, if well pointed. 

You could try putting another 100R resistor in parallel with the one connected to the IR LED to extend the range.

FYI: Most AC units operate on 38kHz.
