### ISSUE TITLE
Remove LED blinking

### ISSUE THREAD

**Issue by bengtmartensson** [z3t0/Arduino-IRremote#462]
Is the LED(-13) blink really a core functionality of the library? Or is it a debug feature that never was taken out? 

Disadvantages: 
* increases porting (and cleanup :-)) effort. 
* increased code size
* Locks up a LED that the user might like to use for some other purpose
* Can be annoying in deployment

Advantages:
* might be useful by initial debugging.
* Looks cool if you like it

Suggestion: take it out.

**Comment by z3t0** [comment]
> Suggestion: take it out.

Agreed.

**Comment by z3t0** [comment]
I have reopened this issue after considering that the LED might actually be useful to the end user. As such I would suggest rather than removing it we address the issues.

For example, it can be disabled on platforms that do not support it and we can add a relevant section in the documentation that explains how to disable the LED for advanced users.

**Comment by bengtmartensson** [comment]
This issue has been resolved (by rejection). The issue thereby can and should therefore be closed.
