### ISSUE TITLE
Different IR-Codes from the same button

### ISSUE THREAD

**Issue by blackdevil8975** [z3t0/Arduino-IRremote#571]
**Board:** ARDUINO UNO
**Library Version:** 2.1.0
**Protocol:** Unknown

I am using the example "IRrecvDumpV2"

I get following results when continuously pressing "On"

```
Encoding : UNKNOWN
Code : 675AFC4B (32 bits)
Timing[11]:
+5250, - 50 +1700, - 100 +1300, - 400 + 800, - 500
+ 50, -2500 + 50
unsigned int rawData[11] = {5250,50, 1700,100, 1300,400, 800,500, 50,2500, 50}; // UNKNOWN 675AFC4B

Encoding : UNKNOWN
Code : 60005DD7 (32 bits)
Timing[23]:
+ 150, - 800 + 250, - 450 +1300, - 200 +1500, - 100
+2450, - 50 +1600, - 50 +2550, -3200 + 50, -5050
+ 200, -1450 + 100, - 300 +1700, - 100 +7650
unsigned int rawData[23] = {150,800, 250,450, 1300,200, 1500,100, 2450,50, 1600,50, 2550,3200, 50,5050, 200,1450, 100,300, 1700,100, 7650}; // UNKNOWN 60005DD7

Encoding : UNKNOWN
Code : 4CB0FADC (32 bits)
Timing[5]:
+9800, -1200 + 50, -1650 + 50
unsigned int rawData[5] = {9800,1200, 50,1650, 50}; // UNKNOWN 4CB0FADC

Encoding : UNKNOWN
Code : 2F5CB35A (32 bits)
Timing[11]:
+2300, - 150 +1600, - 50 +1350, - 50 +3400, - 800
+ 100, -1600 + 100
unsigned int rawData[11] = {2300,150, 1600,50, 1350,50, 3400,800, 100,1600, 100}; // UNKNOWN 2F5CB35A

Encoding : UNKNOWN
Code : D6C35DB (32 bits)
Timing[13]:
+7700, - 50 + 650, - 300 + 700, -1450 + 50, -1650
+ 50, - 350 + 50, - 400 + 50
unsigned int rawData[13] = {7700,50, 650,300, 700,1450, 50,1650, 50,350, 50,400, 50}; // UNKNOWN D6C35DB
```

I get different IR-Codes from the same button.

Im dealing with a TV-Box (PA600C - IP) from Handan BroadinfoCom (http://www.handan.co.kr/index_en.php#page1)
There is no label or model number on the remote.

The detection works fine with my Samsung and LG remote.

Wiring:

![image](https://user-images.githubusercontent.com/17252407/40009874-7f5e8c60-57a3-11e8-9ee3-c30c05e0caa8.png)

I am using a TL1838 Receiver.

**Comment by AnalysIR** [comment]
Wiring looks fine.

I **suspect** the issue is with your IR receiver. Unfortunately, this model is very cheap & can perform poorly.
Try to get a different IR receiver (from Vishay). The TSOP34438 is modern & good quality.

There is a reason those IR receivers are sold for less than $0.10 _(also frequently sold as VS1838)_ :(

For more info: 
[Infrared receiver showdown – TSOP34438 vs VS1838B winner revealed](https://www.analysir.com/blog/2014/12/08/infrared-receiver-showdown-tsop34438-vs-vs1838b-winner-revealed/)

also
[Poor maker’s Infrared receiver](https://www.analysir.com/blog/2014/05/28/poor-makers-infrared-receiver-2/)

Finally, you might get your receiver to work in a dark room & move it away from any WiFi or RF signals.

**Comment by blackdevil8975** [comment]
Thanks for the fast answer.

I just ordered a bunch of the TSOP34438.
I hope it works with them.
