### ISSUE TITLE
Strange behavior on 11 pin Arduino UNO

### ISSUE THREAD

**Issue by uyras** [z3t0/Arduino-IRremote#588]
**Board:** ARDUINO NANO and UNO (328P)
**Library Version:** 2.1.0

Hi, I have a strange behavior with the following code. Arduino stops working after `analogWrite(11, 2);` when you write any number less than 22 to 11 pin. With number >22 it works. Any other pin also works.

**Code Block:**
```c

#include <IRremote.h>

IRrecv irrecv(4);

void setup() {
	irrecv.enableIRIn(); // Start the receiver

	Serial.begin (9600);
	Serial.println ("started");
	Serial.flush();

	pinMode (11, OUTPUT);
	analogWrite(11, 2);
}

int var = 0;
void loop() {
	Serial.println(var++);
	delay(500);
}

```
I tried it both with stable 2.1.0 and beta 2.4.0.

**Comment by AnalysIR** [comment]
pin 11 is connected to Timer2 for PWM on the ATmega238*.

Although, I am not 100% sure how Arduino implements analoguewrite for PWM, it is likely/possible there is some conflict with Timer2 being used by IRremote.

**Workaround Options:**
- Use(configure) Timer1 instead of Timer2 within IRremote
- Use a different pin than pin 11 for the analogue Write to avoid any conflict.

Alternatively, dig into the Arduino implementation of analogueWrite to see what is causing this.
