### ISSUE TITLE
Transmit timing is sensitive to other library ISR

### ISSUE THREAD

**Issue by PaulStoffregen** [z3t0/Arduino-IRremote#89]
The mark() and space() functions use delayMicroseconds(), which is only accurate when no other libraries are consuming much CPU time in their interrupts.

Someday, I'm going to redesign the transmission code to use the timer ISR to enable/disable the PWM output, for reliably transmit timing even when other libraries consume significant CPU time.

This issue is mainly just a reminder to myself to work on this someday....

**Comment by z3t0** [comment]
@PaulStoffregen Just a reminder about this issue. Also, if things have changed and this will not be added we should mark as closed.

**Comment by AnalysIR** [comment]
Another related issue, is that IRremote can only handle pulses with a maximum value of 16,383 uSecs or thereabouts, because of the associated delayMicroseconds limitation. AC protocols often have longer gaps/spaces in between two parts of the signal.

If my memory is correct, passing a value of zero also has unexpected results. e.g. space(0).

Both of these are directly related to the delayMicroseconds implementation in Arduino.

@PaulStoffregen et Al.: if you are considering re-implementation, please consider both of these.

As general comment, a few 10s of uSecs variation in a Mark or Space should not be material for 99% of IR protocols - unless you are using a poor copy of the signal (eg a RAW signal captured with IRremote is 'at least' +/- 50 uSecs by default)

**Comment by ma-laforge** [comment]
You could simply replace the call from delayMicroseconds() with a call to wait_usec(usec_t wTime), as defined in:
https://github.com/ma-laforge/ArduinoCIR/blob/master/libraries/arduino_tools/arduino_ext.h

**Comment by ArminJo** [comment]
is implemented by the custom_delay_usec() function
